[FileDialog]
history=file:///home/hazel/Downloads/tmp, file:///home/hazel/Downloads/smx, file:///home/hazel/Downloads, file:///home/hazel/Downloads/tmp/maps, file:///home/hazel/.steam/steam/steamapps/common/Team Fortress 2/tf/download/maps
lastVisited=file:///home/hazel/Downloads
qtVersion=6.11.1
shortcuts=file:, file:///home/hazel
sidebarWidth=98
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\x1\0\0\0\x3\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x2\x18\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xff\0\0\0\x1\0\0\0\0\0\0\0?\0\0\0\x1\0\0\0\0\0\0\0l\0\0\0\x1\0\0\0\0\0\0\0n\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1)
viewMode=Detail
